### ISSUE TITLE
Application throws error when I use custom ViewHolder(not PinnedViewHolder)

### ISSUE THREAD

**Issue by abekenza** [Joseph82/PinnedList-Android#3]
Application throws error when I use custom ViewHolder(not PinnedViewHolder), actually it crashes when I try to scroll down of the recycler view. 
Is it possible to use custom view holders in PinnedAdapter?

I have got this kind of adapter code.
```java
public class UserListAdapter extends PinnedAdapter {

    private ItemClickListener listener;
    private Context context;

    private static final int VIEW_TYPE_USER = 0;
    private static final int VIEW_TYPE_CONTACT = 1;

    public UserListAdapter(Context context, ItemClickListener listener,
                           GroupListWrapper listGroupWrapper, PinnedListLayout layout) {
        super(listGroupWrapper, layout);
        this.context = context;
        this.listener = listener;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        if (viewType == VIEW_TYPE_CONTACT) {
            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.list_item_contact, parent, false);
            return new ContactViewHolder(view);
        } else {
            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.list_item_user, parent, false);
            return new UserViewHolder(getRowLayout(view));
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
        if (viewHolder instanceof ContactViewHolder) {
            ContactViewHolder holder = (ContactViewHolder) viewHolder;
            //some binding logic
        } else {
            super.onBindViewHolder(viewHolder, position);
            final User user = (User) mListWrapper.getItem(position);
            UserViewHolder holder = (UserViewHolder) viewHolder;
            //some binding logic
        }
    }

    @Override
    public int getItemViewType(int position) {
        if (position < mListWrapper.size()) {
            return VIEW_TYPE_USER;
        } else {
            return VIEW_TYPE_CONTACT;
        }
    }

    @Override
    public int getItemCount() {
        // adding hundred contact view holder items for testing purposes
        return mListWrapper.size() + 100;
    }

    class UserViewHolder extends PinnedViewHolder implements View.OnClickListener {
        @BindView(R.id.icon)
        CircleImageView icon;
        @BindView(R.id.name)
        TextView name;
        @BindView(R.id.status)
        TextView status;

        UserViewHolder(View view) {
            super(view);
            view.setOnClickListener(this);
            ButterKnife.bind(this, view);
        }

        @Override
        public void onClick(View view) {
            if (listener != null) {
                listener.onItemClick(view, getAdapterPosition());
            }
        }
    }

    class ContactViewHolder extends RecyclerView.ViewHolder {
        @BindView(R.id.contact_name)
        TextView name;

        @BindView(R.id.contact_invite)
        Button inviteButton;

        ContactViewHolder(View view) {
            super(view);
            ButterKnife.bind(this, view);
        }
    }
```

Error log
```log
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
                      at java.util.ArrayList.get(ArrayList.java:411)
                      at com.gvillani.pinnedlist.GroupListWrapper.getItemPinned(GroupListWrapper.java:56)
                      at com.gvillani.pinnedlist.PinnedAdapter.getItem(PinnedAdapter.java:66)
                      at com.gvillani.pinnedlist.PinBehavior.isLastItemGroup(PinBehavior.java:347)
                      at com.gvillani.pinnedlist.PinBehavior.updateView(PinBehavior.java:216)
                      at com.gvillani.pinnedlist.PinBehavior.onNestedScroll(PinBehavior.java:211)
                      at android.support.design.widget.CoordinatorLayout.onNestedScroll(CoordinatorLayout.java:1786)
                      at android.support.v4.view.ViewParentCompatLollipop.onNestedScroll(ViewParentCompatLollipop.java:64)
                      at android.support.v4.view.ViewParentCompat$ViewParentCompatLollipopImpl.onNestedScroll(ViewParentCompat.java:177)
                      at android.support.v4.view.ViewParentCompat.onNestedScroll(ViewParentCompat.java:328)
                      at android.support.v4.view.NestedScrollingChildHelper.dispatchNestedScroll(NestedScrollingChildHelper.java:163)
                      at android.support.v7.widget.RecyclerView.dispatchNestedScroll(RecyclerView.java:10462)
                      at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1682)
                      at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2827)
                      at android.view.View.dispatchTouchEvent(View.java:9939)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
                      at android.view.View.dispatchPointerEvent(View.java:10159)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                      at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                      at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                      at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
                      at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                      at android.view.Choreographer.doFrame(Choreographer.java:613)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by Joseph82** [comment]
Of course you can and you should use your custom `ViewHolder`, but you always need to extend `PinnedViewHolder`.

The error you got has nothing to do with the custom `ViewHolder`. 

You are getting that error because your list of item has size 4, but you are telling your adapter that your list size is 104, because of 

```@Override
public int getItemCount() {
     // adding hundred contact view holder items for testing purposes
     return mListWrapper.size() + 100;
}
```
so when you try to the get the item with index 4, the app will crash.
